### ISSUE TITLE
App crashes when I add n() function to summarise block

### ISSUE THREAD

**Issue by Ramdhadage** [blockr-org/blockr.app#22]
App crashes when I add n to funcs in summarise block:

Add data block which have default date set as airquality.
Add summarise block.
Add n from the  funcs dropdown.
Bug: App will crash 
![image](https://github.com/blockr-org/blockr.app/assets/16373721/2d3d4cfe-0775-477c-8b2e-38e186933687)
![image](https://github.com/blockr-org/blockr.app/assets/16373721/770970d3-c2e7-42aa-9d82-e2bba2ee47aa)

**Comment by JohnCoene** [comment]
Thanks, closing, this is a known issue:

https://github.com/blockr-org/blockr/issues/258
