### ISSUE TITLE
App crash when added plot layer block without adding plot block

### ISSUE THREAD

**Issue by Ramdhadage** [blockr-org/blockr.app#9]
App crashes when you add data block and then geom_point block, without adding ggplot block, I have added screenshot for your reference. 

![image](https://github.com/blockr-org/blockr.app/assets/16373721/8b18cd77-c53c-46ad-ba8b-c12c2eaecaa9)
![image](https://github.com/blockr-org/blockr.app/assets/16373721/d7273418-67a7-4942-a754-deb721d0e0c4)

**Comment by JohnCoene** [comment]
There is infrastructure to catch that 

https://github.com/blockr-org/blockr.app/blob/9e52bc93400fba19909db3d254c006333b9c84fd/R/add_stack.R#L69

It was however purposely made more lax for the recent demo because the custom blocks were not registered with the appropriate I/O.

Will fix soon
